name: Ruff
on: [push]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.9.9
          args: "check --extend-select I ./dmd ./examples"
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.9.9
          args: "format --check ./dmd ./examples"
          changed-files: "true"
